name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        working-directory: ./DZDOMOPModel
        run: python -m pip install --upgrade pip wheel build
      - name: Build package
        working-directory: ./DZDOMOPModel
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./DZDOMOPModel/dist
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
